# Generated by Django 4.2 on 2023-04-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_rename_word_words_name_alter_words_learned'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='examples',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
