# Generated by Django 4.2 on 2023-04-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_words_examples'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
