# Generated by Django 4.2 on 2023-04-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0005_lessons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='words',
            old_name='learned',
            new_name='is_learned',
        ),
    ]
